#!/usr/bin/env python3
"""
Mock data for NoorShop — a fictional KSA e-commerce store.
Simulates a real Shopify/Magento backend.
In production, these functions would call the actual platform APIs.
"""

PRODUCTS = [
    {
        "id": "P001",
        "name": "Samsung Galaxy S24 Ultra",
        "name_ar": "سامسونج جالاكسي S24 الترا",
        "category": "electronics",
        "price": 4999,
        "currency": "SAR",
        "stock": 12,
        "description": "6.8-inch display, 200MP camera, 5000mAh battery, S Pen included.",
        "description_ar": "شاشة 6.8 بوصة، كاميرا 200 ميجابكسل، بطارية 5000 مللي أمبير، يأتي مع قلم S.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P002",
        "name": "Nike Air Max 270",
        "name_ar": "نايك اير ماكس 270",
        "category": "footwear",
        "price": 649,
        "currency": "SAR",
        "stock": 34,
        "description": "Sizes 39-46. Available in black, white, and red.",
        "description_ar": "مقاسات 39-46. متوفر بالأسود والأبيض والأحمر.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 1, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P003",
        "name": "Dyson V15 Detect Vacuum",
        "name_ar": "مكنسة دايسون V15",
        "category": "home_appliances",
        "price": 2299,
        "currency": "SAR",
        "stock": 7,
        "description": "Cordless, 60-min runtime, laser dust detection.",
        "description_ar": "لاسلكية، وقت تشغيل 60 دقيقة، كشف الغبار بالليزر.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 4},
        "return_eligible": True,
    },
    {
        "id": "P004",
        "name": "Apple MacBook Air M3",
        "name_ar": "أبل ماك بوك اير M3",
        "category": "electronics",
        "price": 5499,
        "currency": "SAR",
        "stock": 0,
        "description": "13-inch, 8GB RAM, 256GB SSD, 18-hour battery.",
        "description_ar": "13 بوصة، 8 جيجا رام، 256 جيجا SSD، بطارية 18 ساعة.",
        "delivery_days": {"Riyadh": 3, "Jeddah": 4, "Dammam": 4, "other": 5},
        "return_eligible": True,
        "restock_date": "2026-03-25",
    },
    {
        "id": "P005",
        "name": "Zara Linen Abaya",
        "name_ar": "عباءة كتان زارا",
        "category": "fashion",
        "price": 399,
        "currency": "SAR",
        "stock": 22,
        "description": "Premium linen, sizes XS-XL, multiple colors.",
        "description_ar": "كتان فاخر، مقاسات XS-XL، ألوان متعددة.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 1, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P006",
        "name": "Nespresso Vertuo Next",
        "name_ar": "ماكينة نسبريسو فيرتو نكست",
        "category": "kitchen",
        "price": 849,
        "currency": "SAR",
        "stock": 15,
        "description": "Compatible with Vertuo capsules. 5 cup sizes.",
        "description_ar": "متوافقة مع كبسولات فيرتو. 5 أحجام للقهوة.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P007",
        "name": "Philips Hue Starter Kit",
        "name_ar": "طقم فيليبس هيو الذكي",
        "category": "smart_home",
        "price": 549,
        "currency": "SAR",
        "stock": 9,
        "description": "3 smart bulbs + bridge. Works with Alexa & Google Home.",
        "description_ar": "3 مصابيح ذكية + جهاز التحكم. يعمل مع أليكسا وجوجل هوم.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P008",
        "name": "Adidas Ultraboost 23",
        "name_ar": "أديداس ألترا بوست 23",
        "category": "footwear",
        "price": 750,
        "currency": "SAR",
        "stock": 18,
        "description": "Running shoes, sizes 39-47. Boost cushioning.",
        "description_ar": "أحذية جري، مقاسات 39-47. وسادة بوست.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 1, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P009",
        "name": "Sony WH-1000XM5 Headphones",
        "name_ar": "سماعات سوني WH-1000XM5",
        "category": "electronics",
        "price": 1599,
        "currency": "SAR",
        "stock": 5,
        "description": "Industry-leading noise cancellation. 30-hour battery.",
        "description_ar": "أفضل عزل للضوضاء في فئتها. بطارية 30 ساعة.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P010",
        "name": "L'Occitane Shea Butter Gift Set",
        "name_ar": "طقم هدايا لوكسيتان بزبدة الشيا",
        "category": "beauty",
        "price": 299,
        "currency": "SAR",
        "stock": 30,
        "description": "Body lotion, hand cream, and lip balm set.",
        "description_ar": "طقم يحتوي على غسول الجسم وكريم اليدين وبلسم الشفاه.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 1, "Dammam": 2, "other": 3},
        "return_eligible": False,  # cosmetics non-returnable
    },
    {
        "id": "P011",
        "name": "iPad Pro 13-inch M4",
        "name_ar": "آيباد برو 13 بوصة M4",
        "category": "electronics",
        "price": 6299,
        "currency": "SAR",
        "stock": 6,
        "description": "13-inch Liquid Retina XDR display, M4 chip, 256GB, Wi-Fi + Cellular.",
        "description_ar": "شاشة Liquid Retina XDR 13 بوصة، شريحة M4، 256 جيجابايت، واي فاي وخلوي.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 4},
        "return_eligible": True,
    },
    {
        "id": "P012",
        "name": "Instant Pot Duo 7-in-1",
        "name_ar": "قدر إنستانت بوت 7 في 1",
        "category": "kitchen",
        "price": 499,
        "currency": "SAR",
        "stock": 20,
        "description": "6-quart electric pressure cooker. Replaces 7 appliances.",
        "description_ar": "قدر كهربائي سريع الضغط 6 كوارت. يستبدل 7 أجهزة مطبخية.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 1, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P013",
        "name": "Levi's 501 Original Jeans",
        "name_ar": "جينز ليفايز 501 الأصلي",
        "category": "fashion",
        "price": 349,
        "currency": "SAR",
        "stock": 45,
        "description": "Classic straight fit. Sizes 28-38. Stonewash and indigo.",
        "description_ar": "قصة مستقيمة كلاسيكية. مقاسات 28-38. ألوان حجري وإنديجو.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 1, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P014",
        "name": "Xiaomi Robot Vacuum X10+",
        "name_ar": "مكنسة شاومي روبوت X10+",
        "category": "home_appliances",
        "price": 1799,
        "currency": "SAR",
        "stock": 11,
        "description": "4000Pa suction, auto empty base, LiDAR mapping, mop function.",
        "description_ar": "شفط 4000 باسكال، قاعدة تفريغ تلقائي، خريطة ليدار، وظيفة مسح.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 4},
        "return_eligible": True,
    },
    {
        "id": "P015",
        "name": "JBL Flip 6 Bluetooth Speaker",
        "name_ar": "سماعة JBL فليب 6 بلوتوث",
        "category": "electronics",
        "price": 449,
        "currency": "SAR",
        "stock": 0,
        "description": "IP67 waterproof, 12-hour battery, powerful bass. Available in 6 colors.",
        "description_ar": "مقاومة للماء IP67، بطارية 12 ساعة، باس قوي. متوفر بـ6 ألوان.",
        "delivery_days": {"Riyadh": 2, "Jeddah": 3, "Dammam": 3, "other": 5},
        "return_eligible": True,
        "restock_date": "2026-03-28",
    },
    {
        "id": "P016",
        "name": "Puma RS-X Sneakers",
        "name_ar": "حذاء بوما RS-X",
        "category": "footwear",
        "price": 429,
        "currency": "SAR",
        "stock": 27,
        "description": "Retro chunky sole, sizes 38-46. White/blue colorway.",
        "description_ar": "نعل سميك ريترو، مقاسات 38-46. لون أبيض وأزرق.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 1, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P017",
        "name": "Nespresso Aeroccino 4 Frother",
        "name_ar": "جهاز إيروتشينو 4 لإعداد الرغوة",
        "category": "kitchen",
        "price": 349,
        "currency": "SAR",
        "stock": 14,
        "description": "Hot and cold milk frother. Four frothing modes.",
        "description_ar": "جهاز رغوة الحليب الساخن والبارد. أربعة أوضاع.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
    {
        "id": "P018",
        "name": "Amazon Echo Show 10",
        "name_ar": "أمازون إيكو شو 10",
        "category": "smart_home",
        "price": 999,
        "currency": "SAR",
        "stock": 8,
        "description": "10-inch HD display, Alexa, 360° rotating screen, smart home hub.",
        "description_ar": "شاشة HD 10 بوصة، أليكسا، شاشة دوارة 360 درجة، محور المنزل الذكي.",
        "delivery_days": {"Riyadh": 1, "Jeddah": 2, "Dammam": 2, "other": 3},
        "return_eligible": True,
    },
]

ORDERS = [
    {
        "id": "ORD-1042",
        "customer_email": "ahmed@example.com",
        "customer_name": "Ahmed Al-Rashid",
        "status": "out_for_delivery",
        "status_ar": "خارج للتوصيل",
        "items": [{"product_id": "P002", "name": "Nike Air Max 270", "qty": 1, "price": 649}],
        "total": 649,
        "currency": "SAR",
        "payment_method": "credit_card",
        "order_date": "2026-03-14",
        "estimated_delivery": "2026-03-16",
        "tracking_number": "ARAMEX-9948271",
        "delivery_city": "Riyadh",
        "return_window_days": 14,
    },
    {
        "id": "ORD-0987",
        "customer_email": "sara@example.com",
        "customer_name": "Sara Al-Otaibi",
        "status": "delivered",
        "status_ar": "تم التوصيل",
        "items": [{"product_id": "P005", "name": "Zara Linen Abaya", "qty": 2, "price": 798}],
        "total": 798,
        "currency": "SAR",
        "payment_method": "cod",
        "order_date": "2026-03-10",
        "delivered_date": "2026-03-12",
        "tracking_number": "SMSA-7712934",
        "delivery_city": "Jeddah",
        "return_window_days": 14,
        "return_deadline": "2026-03-26",
    },
    {
        "id": "ORD-1105",
        "customer_email": "khalid@example.com",
        "customer_name": "Khalid Al-Zahrani",
        "status": "processing",
        "status_ar": "قيد المعالجة",
        "items": [
            {"product_id": "P001", "name": "Samsung Galaxy S24 Ultra", "qty": 1, "price": 4999},
            {"product_id": "P009", "name": "Sony WH-1000XM5", "qty": 1, "price": 1599},
        ],
        "total": 6598,
        "currency": "SAR",
        "payment_method": "credit_card",
        "order_date": "2026-03-15",
        "estimated_delivery": "2026-03-17",
        "delivery_city": "Dammam",
        "return_window_days": 14,
    },
    {
        "id": "ORD-0854",
        "customer_email": "fatima@example.com",
        "customer_name": "Fatima Al-Ghamdi",
        "status": "cancelled",
        "status_ar": "ملغى",
        "items": [{"product_id": "P003", "name": "Dyson V15 Detect", "qty": 1, "price": 2299}],
        "total": 2299,
        "currency": "SAR",
        "payment_method": "credit_card",
        "order_date": "2026-03-08",
        "cancelled_date": "2026-03-09",
        "refund_status": "refunded",
        "refund_date": "2026-03-11",
        "delivery_city": "Riyadh",
        "return_window_days": 0,
    },
    {
        "id": "ORD-1200",
        "customer_email": "omar@example.com",
        "customer_name": "Omar Al-Shammari",
        "status": "shipped",
        "status_ar": "تم الشحن",
        "items": [{"product_id": "P006", "name": "Nespresso Vertuo Next", "qty": 1, "price": 849}],
        "total": 849,
        "currency": "SAR",
        "payment_method": "credit_card",
        "order_date": "2026-03-14",
        "estimated_delivery": "2026-03-17",
        "tracking_number": "DHL-4421887",
        "delivery_city": "Riyadh",
        "return_window_days": 14,
    },
    {
        "id": "ORD-1188",
        "customer_email": "nora@example.com",
        "customer_name": "Nora Al-Dosari",
        "status": "delivered",
        "status_ar": "تم التوصيل",
        "items": [{"product_id": "P010", "name": "L'Occitane Gift Set", "qty": 1, "price": 299}],
        "total": 299,
        "currency": "SAR",
        "payment_method": "cod",
        "order_date": "2026-03-11",
        "delivered_date": "2026-03-13",
        "tracking_number": "SMSA-8892011",
        "delivery_city": "Jeddah",
        "return_window_days": 0,  # cosmetics non-returnable
    },
    {
        "id": "ORD-1301",
        "customer_email": "lina@example.com",
        "customer_name": "Lina Al-Harbi",
        "status": "delivered",
        "status_ar": "تم التوصيل",
        "items": [
            {"product_id": "P011", "name": "iPad Pro 13-inch M4", "qty": 1, "price": 6299},
        ],
        "total": 6299,
        "currency": "SAR",
        "payment_method": "credit_card",
        "order_date": "2026-03-09",
        "delivered_date": "2026-03-11",
        "tracking_number": "ARAMEX-5561029",
        "delivery_city": "Riyadh",
        "return_window_days": 14,
        "return_deadline": "2026-03-25",
    },
    {
        "id": "ORD-1350",
        "customer_email": "tariq@example.com",
        "customer_name": "Tariq Al-Mutairi",
        "status": "out_for_delivery",
        "status_ar": "خارج للتوصيل",
        "items": [
            {"product_id": "P014", "name": "Xiaomi Robot Vacuum X10+", "qty": 1, "price": 1799},
            {"product_id": "P017", "name": "Nespresso Aeroccino 4", "qty": 1, "price": 349},
        ],
        "total": 2148,
        "currency": "SAR",
        "payment_method": "credit_card",
        "order_date": "2026-03-16",
        "estimated_delivery": "2026-03-18",
        "tracking_number": "DHL-7734512",
        "delivery_city": "Dammam",
        "return_window_days": 14,
    },
    {
        "id": "ORD-1410",
        "customer_email": "maha@example.com",
        "customer_name": "Maha Al-Qahtani",
        "status": "processing",
        "status_ar": "قيد المعالجة",
        "items": [
            {"product_id": "P018", "name": "Amazon Echo Show 10", "qty": 1, "price": 999},
            {"product_id": "P013", "name": "Levi's 501 Jeans", "qty": 2, "price": 698},
        ],
        "total": 1697,
        "currency": "SAR",
        "payment_method": "cod",
        "order_date": "2026-03-17",
        "estimated_delivery": "2026-03-20",
        "delivery_city": "Riyadh",
        "return_window_days": 14,
    },
]

RETURN_POLICY = {
    "window_days": 14,
    "conditions": [
        "Item must be unused and in original packaging",
        "Electronics must include all accessories and manuals",
        "Cosmetics and personal care items are non-returnable",
        "Sale items marked as final sale cannot be returned",
    ],
    "process": "Initiate online → print label → drop at SMSA/Aramex point",
    "refund_timeline": {
        "credit_card": "3-5 business days",
        "cod": "Bank transfer within 7 business days — customer must provide IBAN",
    },
    "non_returnable_categories": ["beauty", "cosmetics", "underwear", "swimwear"],
}

PROMO_CODES = [
    {
        "code": "SAVE10",
        "discount_type": "percentage",
        "discount_value": 10,
        "min_order": 200,
        "active": True,
        "description": "10% off orders over 200 SAR",
    },
    {
        "code": "WELCOME50",
        "discount_type": "fixed",
        "discount_value": 50,
        "min_order": 300,
        "active": True,
        "description": "50 SAR off your first order over 300 SAR",
    },
    {
        "code": "FREESHIP",
        "discount_type": "shipping",
        "discount_value": 0,
        "min_order": 0,
        "active": True,
        "description": "Free shipping on any order",
    },
]

STORE_INFO = {
    "name": "NoorShop",
    "name_ar": "نور شوب",
    "support_hours": "Sun–Thu 9AM–10PM, Fri–Sat 12PM–10PM (AST)",
    "support_email": "support@noorshop.sa",
    "support_phone": "+1 415 523 8886",
    "whatsapp": "+14155238886",
    "shipping_fee": 25,
    "free_shipping_threshold": 300,
    "currency": "SAR",
}
